// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ8TLoka1RUqYZKRZCHplHdEEKTHA--lI',
    appId: '1:766987145940:web:baeb0f266eb0a1f982a141',
    messagingSenderId: '766987145940',
    projectId: 'coaching-app-711ea',
    authDomain: 'coaching-app-711ea.firebaseapp.com',
    storageBucket: 'coaching-app-711ea.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDgK1_6YlldoDWMGhJh7EbKCLNFAgcUXU',
    appId: '1:766987145940:android:7a903e6080a6fc7682a141',
    messagingSenderId: '766987145940',
    projectId: 'coaching-app-711ea',
    storageBucket: 'coaching-app-711ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoGF1-heGKRCAI-y4tRFmB1cBS_MRjGCQ',
    appId: '1:766987145940:ios:997643862ee1ad8082a141',
    messagingSenderId: '766987145940',
    projectId: 'coaching-app-711ea',
    storageBucket: 'coaching-app-711ea.appspot.com',
    iosBundleId: 'com.example.coachingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoGF1-heGKRCAI-y4tRFmB1cBS_MRjGCQ',
    appId: '1:766987145940:ios:f242e276f118589182a141',
    messagingSenderId: '766987145940',
    projectId: 'coaching-app-711ea',
    storageBucket: 'coaching-app-711ea.appspot.com',
    iosBundleId: 'com.example.coachingApp.RunnerTests',
  );
}
